### ISSUE TITLE
java.lang.NullPointerException at at de.markiewb.netbeans.plugins.hints.structure.MethodNameHint.convert

### ISSUE THREAD

**Issue by markiewb** [markiewb/nb-additional-hints#64]
java.lang.NullPointerException
   at org.netbeans.api.java.source.ElementUtilities.enclosingTypeElementImpl(ElementUtilities.java:154)
   at org.netbeans.api.java.source.ElementUtilities.enclosingTypeElement(ElementUtilities.java:149)
   at de.markiewb.netbeans.plugins.hints.structure.MethodNameHint.convert(MethodNameHint.java:79)
   at sun.reflect.GeneratedMethodAccessor75.invoke(GeneratedMethodAccessor75.java:0)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:497)

https://netbeans.org/bugzilla/show_bug.cgi?id=257393

**Comment by markiewb** [comment]
Fixed in 1.6.0.5
