### ISSUE TITLE
NullPointerException at org.netbeans.api.java.source.ElementUtilities.enclosingTypeElementImpl

### ISSUE THREAD

**Issue by markiewb** [markiewb/nb-additional-hints#77]
https://netbeans.org/bugzilla/show_bug.cgi?id=268366

```
Stacktrace: 
java.lang.NullPointerException
   at org.netbeans.api.java.source.ElementUtilities.enclosingTypeElementImpl(ElementUtilities.java:159)
   at org.netbeans.api.java.source.ElementUtilities.enclosingTypeElement(ElementUtilities.java:154)
   at de.markiewb.netbeans.plugins.hints.structure.MethodNameHint.convert(MethodNameHint.java:79)
   at sun.reflect.GeneratedMethodAccessor120.invoke(GeneratedMethodAccessor120.java:0)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by markiewb** [comment]
Already solved by https://github.com/markiewb/nb-additional-hints/issues/64
